#!/usr/bin/env python3
"""Generate src/Assets.php for the PHP project from the C# ground truth.

Pay-by-Square-cs's src/TileAssets.cs holds the canonical baked wordmark
(CAP_RGBA, 470x76) and brand icon (ICON_RGBA, 64x64) as packed int[]
(alpha<<24 | r<<16 | g<<8 | b, row-major, row 0 = top) plus the exact
segment widths used by the C# and SVG renderers.

Rather than re-bake fonts (risk of glyph drift), PHP re-uses the EXACT
same RGBA source — this file parses TileAssets.cs and emits an equivalent
PHP facade with byte-identical pixels:

  Assets::$CAP_W / Assets::$CAP_H   wordmark size
  Assets::$ICON                     icon edge
  Assets::$CAP_RGBA / Assets::$ICON_RGBA  unpacked [r,g,b,a] triples
  Assets::capPixel(x,y) / Assets::iconPixel(x,y)
  Assets::$SEG_PAY / $SEG_GAP / $SEG_BY   /1024 segment widths (SVG parity)
"""
import re, sys

CS = '/home/aido/Projects/Pay-by-Square-cs/src/TileAssets.cs'
OUT = sys.argv[1] if len(sys.argv) > 1 else \
      '/home/aido/Projects/Pay-by-Square-php/src/Assets.php'

txt = open(CS).read()
const = lambda name: int(re.search(rf'{name}\s*=\s*(\d+)\s*;', txt).group(1))
capw, caph, icon = const('CapW'), const('CapH'), const('IconSize')

def arr(name, count):
    m = re.search(rf'{name}\s*=\s*new int\[{re.escape(str(count))}\]\s*\{{(.*?)\}}\s*;',
                  txt, re.S)
    if not m:
        sys.exit(f'cannot find {name}[{count}] in TileAssets.cs')
    vals = re.findall(r'-?0x[0-9a-fA-F]{1,8}', m.group(1))
    if len(vals) != count:
        sys.exit(f'{name}: expected {count} values, found {len(vals)}')
    out = []
    for v in vals:
        n = int(v, 16)
        if n & 0x80000000:
            n -= 0x100000000          # signed 32-bit two's complement
        n &= 0xFFFFFFFF
        a, r, g, b = (n >> 24) & 255, (n >> 16) & 255, (n >> 8) & 255, n & 255
        out.append((r, g, b, a))
    return out

cap       = arr('CAP_RGBA',   capw * caph)
icon_rgba = arr('ICON_RGBA',  icon * icon)

def seg(name):
    m = re.search(rf'{name}\s*=\s*(\d+)\s*;', txt)
    return int(m.group(1)) if m else 0
seg_pay, seg_gap, seg_by = seg('SegPay'), seg('SegGap'), seg('SegBy')
if not (seg_pay or seg_gap or seg_by):
    sys.exit('TileAssets.cs lacks SegPay/SegGap/SegBy — rebuild C# with '
             'tools/gen_caps_assets.py first (SVG caption parity needs them)')

def rgba_list(items, per_line=16, indent='        '):
    lines, line, n = [], [], 0
    for (r, g, b, a) in items:
        if n >= per_line:
            lines.append(indent + ', '.join(line) + ',')
            line, n = [], 0
        line.append(f'[{r},{g},{b},{a}]')
        n += 1
    if line:
        lines.append(indent + ', '.join(line) + ',')
    return '\n'.join(lines)

TEMPLATE = r'''<?php
declare(strict_types=1);
namespace Pbs;

/**
 * Baked tile assets — the canonical "PAY by square" wordmark and brand
 * icon, byte-identical to the C# ground truth (Pay-by-Square-cs
 * src/TileAssets.cs). Generated by tools/gen_assets.py — re-run the C#
 * baker (tools/gen_caps_assets.py) then this generator; never hand-edit
 * pixels.
 *
 * Packing note: the C# facade returns (r,g,b,a) from an int
 * (a<<24)|(r<<16)|(g<<8)|b. PHP stores the unpacked [r,g,b,a] arrays
 * (row-major, row 0 = top of the asset) — cheaper to sample, identical
 * source.
 */
final class Assets
{
    public const CAP_W   = @CAPW@;
    public const CAP_H   = @CAPH@;
    public const ICON    = @ICON@;
    // Wordmark segment widths in /1024 of CAP_W (SVG caption parity,
    // 'PAY' | gap | 'by square').
    public const SEG_PAY = @SEG_PAY@;
    public const SEG_GAP = @SEG_GAP@;
    public const SEG_BY  = @SEG_BY@;

    /** @var list<int> [r,g,b,a] arrays, row-major (CAP_W*CAP_H pixels). */
    public static array $CAP_RGBA = [
@CAP_BODY@
    ];

    /** @var list<int> [r,g,b,a] arrays, row-major (ICON*ICON pixels). */
    public static array $ICON_RGBA = [
@ICON_BODY@
    ];

    /** Sample the wordmark at (x,y) as int[] {r,g,b,a}; transparent out of range. */
    public static function capPixel(int $x, int $y): array
    {
        if ($x < 0 || $x >= self::CAP_W || $y < 0 || $y >= self::CAP_H) {
            return [0, 0, 0, 0];
        }
        return self::$CAP_RGBA[$y * self::CAP_W + $x];
    }

    /** Sample the icon at (x,y) as int[] {r,g,b,a}; transparent out of range. */
    public static function iconPixel(int $x, int $y): array
    {
        if ($x < 0 || $x >= self::ICON || $y < 0 || $y >= self::ICON) {
            return [0, 0, 0, 0];
        }
        return self::$ICON_RGBA[$y * self::ICON + $x];
    }
}
'''
php = (TEMPLATE
       .replace('@CAPW@',      str(capw))
       .replace('@CAPH@',      str(caph))
       .replace('@ICON@',      str(icon))
       .replace('@SEG_PAY@',   str(seg_pay))
       .replace('@SEG_GAP@',   str(seg_gap))
       .replace('@SEG_BY@',    str(seg_by))
       .replace('@CAP_BODY@',  rgba_list(cap))
       .replace('@ICON_BODY@', rgba_list(icon_rgba)))
open(OUT, 'w').write(php)
print(f'{OUT}: CAP={capw}x{caph} ({len(cap)} px), ICON={icon}, '
      f'SEG=({seg_pay},{seg_gap},{seg_by}), {len(php)} bytes')
